### ISSUE TITLE
Adding methods to removing events and games

### ISSUE THREAD

**Issue by ToadKing** [cschuller/gamesense-client#4]
SteelSeries Engine 3.5.0 now includes APIs for deleting game events and games. [[1]](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/writing-handlers-in-json.md#removing-an-event) [[2]](https://github.com/SteelSeries/gamesense-sdk/blob/master/doc/api/writing-handlers-in-json.md#removing-a-game) So manually editing the SQLite database isn't necessary anymore.

**Comment by chris-zeitport** [comment]
Thanks for the API improvement. I will add this features and also update the README.md file.

**Comment by chris-zeitport** [comment]
Issue will be implemented, when GameSense Engine 3.5.x will be released.
