### ISSUE TITLE
Tactile Effects

### ISSUE THREAD

**Issue by iFeelPixel** [cschuller/gamesense-client#6]
Hi Christian,
Thanks for your developement.
I would really appreciate if you can update GamseSense client because SteelSeries Developers have implemented new functions to control the haptic motors (See JSON tactile handlers) in GameSense SDK:
https://github.com/SteelSeries/gamesense-sdk/blob/5945027e3d950af7e688d95f0180872ce44d073d/doc/api/json-handlers-tactile.md
Can you add  examples to turn on/off the motor in a next Gamesense-client update, please?
The following code allows to blink color the Rival 700
var functionKeysEventHandler = new gamesense.GameEventHandler(gamesense.DeviceType.MOUSE, gamesense.tactile, blinkColor);
For information, there are 2 tactile mouse devices "Rival 700" and "Rival 500".
Best regards,
Frederic

**Comment by chris-zeitport** [comment]
I will take a look at it, but no promises...

**Comment by chris-zeitport** [comment]
This personal side-project will no longer be active. I hope it helped you or you found it useful. Feel free to fork it.
